plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.21' apply false
    id 'net.darkhax.curseforgegradle' version "${cursegradle_version}" apply false
    id "com.modrinth.minotaur" version "2.+" apply false
}

subprojects {
    configurations.all {
        resolutionStrategy {
            cacheChangingModulesFor 60, 'seconds'
            cacheDynamicVersionsFor 60, 'seconds'
        }
    }

    ext {
        rawVersion = project.version
    }
}

task publishCurseForge(dependsOn: [':Fabric:publishCurseForgeFabric']) {
}

task publishModrinth(dependsOn: [':Fabric:modrinth']) {
}

task publishCurseAndModrinth(dependsOn: ['publishCurseForge', 'publishModrinth']) {
}
